[package]
name = "nss_himmelblau"
edition.workspace = true
license.workspace = true
homepage.workspace = true
version.workspace = true

[lib]
name = "nss_himmelblau"
crate-type = [ "cdylib" ]
path =  "src/lib.rs"

[dependencies]
libc = "0.2.155"
libnss = "0.8.0"
ntstatus_gen.workspace = true
param = { workspace = true }
sock = { workspace = true }

[build-dependencies]
version = { path = "../version" }
