[package]
name = "sock"
edition.workspace = true
license.workspace = true
homepage.workspace = true
version.workspace = true

[dependencies]
libc.workspace = true
libnss = "0.8.0"
ntstatus_gen.workspace = true
param.workspace = true
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
